### ISSUE TITLE
Problem with new CouchDB and InfluxDB setup in CLI?

### ISSUE THREAD

**Issue by flomickl** [apache/streampipes#1221]
### Body

I worked in the branch SP-584 mentioned here
https://github.com/apache/streampipes/pull/1044#issuecomment-1416032823

I did a clean docker system prune because it was not necessary to persist the data. All containers and volumes were removed!
But something is wrong with the CouchDB and Influx DB versions after a new start.

```
influxdb:2.6                                                    treampipes-influxdb-1
couchdb:3.3.1                                                   streampipes-couchdb-1d


local     4456cd6e5bfd5780a8421b310e72a317c222006bde5f718a1c647775128d3941
local     streampipes_backend
local     streampipes_consul
local     streampipes_couchdb
local     streampipes_files
local     streampipes_influxdb
local     streampipes_influxdb2
local     streampipes_kafka
local     streampipes_nginx
local     streampipes_zookeeper
```

Is this a correct behavior?

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by dominikriemer** [comment]
@flomickl what exactly is the wrong behaviour? Is anything working not as expected? From the screenshots, it looks ok at first glance, at least I can't spot a problem...

**Comment by flomickl** [comment]
There are two volumes now

local     streampipes_influxdb
local     streampipes_influxdb2

and a dangling unnamed volume 
local     4456cd6e5bfd5780a8421b310e72a317c222006bde5f718a1c647775128d3941

**Comment by flomickl** [comment]
@dominikriemer ok there seems to be a problem
I can't even start the machine data simulator

**Comment by flomickl** [comment]
Hm, I switched now to the dev branch and 
did a docker system prune again to have a clean start.

The backend container is exiting on start:
Do I have to set some new credentials in the CLI  again?

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'streamPipesBackendApplication': Invocation of init method failed
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:195)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:420)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1743)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:961)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:915)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
        at org.apache.streampipes.service.base.StreamPipesServiceBase.runApplication(StreamPipesServiceBase.java:50)
        at org.apache.streampipes.service.base.StreamPipesServiceBase.startStreamPipesService(StreamPipesServiceBase.java:43)
        at org.apache.streampipes.service.core.StreamPipesBackendApplication.main(StreamPipesBackendApplication.java:90)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: org.lightcouch.CouchDbException: Unauthorized{"error":"unauthorized","reason":"Name or password is incorrect."}

        at org.lightcouch.CouchDbClientBase.validate(CouchDbClientBase.java:659)
        at org.lightcouch.CouchDbClient$3.process(CouchDbClient.java:223)
        at org.apache.http.protocol.ImmutableHttpProcessor.process(ImmutableHttpProcessor.java:142)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:191)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at org.lightcouch.CouchDbClientBase.executeRequest(CouchDbClientBase.java:480)
        at org.lightcouch.CouchDbClientBase.get(CouchDbClientBase.java:531)
        at org.lightcouch.CouchDbClientBase.get(CouchDbClientBase.java:542)
        at org.lightcouch.CouchDbContext.createDB(CouchDbContext.java:83)
        at org.lightcouch.CouchDbContext.<init>(CouchDbContext.java:55)
        at org.lightcouch.CouchDbClientBase.<init>(CouchDbClientBase.java:102)
        at org.lightcouch.CouchDbClient.<init>(CouchDbClient.java:128)
        at org.apache.streampipes.storage.couchdb.utils.Utils.getCouchDbRdfEndpointClient(Utils.java:112)
        at org.apache.streampipes.storage.couchdb.dao.DbCommand.execute(DbCommand.java:38)
        at org.apache.streampipes.storage.couchdb.dao.CrudDao.findAll(CrudDao.java:61)
        at org.apache.streampipes.storage.couchdb.dao.AbstractDao.findAll(AbstractDao.java:56)
        at org.apache.streampipes.storage.couchdb.impl.ExtensionsServiceEndpointStorageImpl.getExtensionsServiceEndpoints(ExtensionsServiceEndpointStorageImpl.java:47)
        at org.apache.streampipes.manager.endpoint.EndpointFetcher.getEndpoints(EndpointFetcher.java:43)
        at org.apache.streampipes.manager.setup.InstallationConfiguration.getInstallationSteps(InstallationConfiguration.java:53)
        at org.apache.streampipes.manager.setup.AutoInstallation.startAutoInstallation(AutoInstallation.java:39)
        at org.apache.streampipes.service.core.StreamPipesBackendApplication.doInitialSetup(StreamPipesBackendApplication.java:149)
        at org.apache.streampipes.service.core.StreamPipesBackendApplication.init(StreamPipesBackendApplication.java:115)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:424)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:368)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:192)
        ... 26 common frames omitted`
```

**Comment by dominikriemer** [comment]
The two influx volumes are ok (we need the old volume for backwards compatibility). When using the `upgrade` flag, data from v1 is migrated to the new volume. In the version after the next release, we would remove the influx volume and only use the v2 volume.
Concerning your second error, there are credentials defined in the CLI and the docker compose files: `COUCHDB_USER` and `COUCHDB_PASSWORD`. Can you please check that these variables are present?

**Comment by flomickl** [comment]
ah ok. The next day the error was gone anyway, So don't know why the error occurred. Everything is working as expected!
