### ISSUE TITLE
400 error with using email notification

### ISSUE THREAD

**Issue by bosseedi** [apache/streampipes#2461]
### Apache StreamPipes version

dev (current development state)

### Affected StreamPipes components

Processing Elements

### What happened?

Streampipes is running in kubernetes installed with helm.
Under configuration / email the configuration is done and it was possibly to receive to receive the test email.
But the email notification from inside the pipeline does not work. In the extensions-all-iiot pod the following error message can be seen:

2024-02-07T13:47:14.155Z ERROR 1 --- [         nats:3] o.a.s.w.s.r.StandaloneEventSinkRuntime   : RuntimeException while processing event in org.apache.streampipes.sinks.notifications.jvm.email.EmailSink                                                                   

org.apache.streampipes.commons.exceptions.SpHttpErrorStatusCode: 400 -
        at org.apache.streampipes.client.http.HttpRequest.executeRequest(HttpRequest.java:112)
        at org.apache.streampipes.client.api.AbstractClientApi.post(AbstractClientApi.java:58)
        at org.apache.streampipes.client.api.CustomRequestApi.sendPost(CustomRequestApi.java:33)
        at org.apache.streampipes.client.StreamPipesClient.deliverEmail(StreamPipesClient.java:231)
        at org.apache.streampipes.sinks.notifications.jvm.email.EmailSink.onNotificationEvent(EmailSink.java:89)
        at org.apache.streampipes.wrapper.standalone.StreamPipesNotificationSink.onEvent(StreamPipesNotificationSink.java:93)
        at org.apache.streampipes.wrapper.standalone.runtime.StandaloneEventSinkRuntime.process(StandaloneEventSinkRuntime.java:55)
        at org.apache.streampipes.wrapper.standalone.routing.StandaloneSpInputCollector.send(StandaloneSpInputCollector.java:56)
        at org.apache.streampipes.wrapper.standalone.routing.StandaloneSpInputCollector.lambda$onEvent$0(StandaloneSpInputCollector.java:51)                                                                                                                                  
        at java.base/java.util.concurrent.ConcurrentHashMap.forEach(Unknown Source)
        at org.apache.streampipes.wrapper.standalone.routing.StandaloneSpInputCollector.onEvent(StandaloneSpInputCollector.java:51)
        at org.apache.streampipes.wrapper.standalone.routing.StandaloneSpInputCollector.onEvent(StandaloneSpInputCollector.java:30)
        at org.apache.streampipes.messaging.nats.NatsConsumer.lambda$createSubscription$1(NatsConsumer.java:83)
        at io.nats.client.impl.NatsDispatcher.run(NatsDispatcher.java:93)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

What can be done to fix this error?

### How to reproduce?

Configure the mail settings under configuration / mail and send a test mail which is delivered.
Create a pipeline with a mqtt adapter and a email notification.
No email notifications are sent, an error can be seen in extensions-all-iiot

### Expected behavior

As far as I understand this is an internal request to /api/v2/mail which is failing. In our mail server we could also not see a connection attempt

### Additional technical information

streampipes dev version, runs in kubernetes, installed with helm

### Are you willing to submit a PR?

None

**Comment by dominikriemer** [comment]
Hi @bosseedi thanks for reporting this!
I created a PR with a fix.
The error probably appears when the email template contains placeholders which are not set by the email sink (in my case it's PREHEADER and TITLE. So as a quick workaround before the next release you could try to remove these placeholders from your email template.
