### ISSUE TITLE
NullPointer Exception in Flink pattern detection processor

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#453]
There is a bug in the Sequence pattern detection processing for Flink currently leading to a Nullpointer Exception in this method:
```

@Override
public void processElement1(Event value, Context ctx, Collector<Event> out) throws Exception
{
 state.update(new EventStorage(System.currentTimeMillis(), value));
}
```

See error log:
```

pipeline-elements-all-flink_1  | Caused by: java.lang.NullPointerException
pipeline-elements-all-flink_1
 | 	at org.apache.streampipes.processors.pattern.detection.flink.processor.sequence.Sequence.processElement1(Sequence.java:48)
pipeline-elements-all-flink_1
 | 	at org.apache.streampipes.processors.pattern.detection.flink.processor.sequence.Sequence.processElement1(Sequence.java:26)
pipeline-elements-all-flink_1
 | 	at org.apache.flink.streaming.api.operators.co.LegacyKeyedCoProcessOperator.processElement1(LegacyKeyedCoProcessOperator.java:81)
pipeline-elements-all-flink_1
 | 	at org.apache.flink.streaming.runtime.io.StreamTwoInputProcessor.processInput(StreamTwoInputProcessor.java:259)
pipeline-elements-all-flink_1
 | 	at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:279)
pipeline-elements-all-flink_1
 | 	at org.apache.flink.streaming.runtime.tasks.StreamTask.run(StreamTask.java:301)
pipeline-elements-all-flink_1
 | 	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:406)
pipeline-elements-all-flink_1
 | 	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:705)
pipeline-elements-all-flink_1
 | 	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:530)
pipeline-elements-all-flink_1 
| 	at java.lang.Thread.run(Unknown Source)

```

Imported from Jira [STREAMPIPES-283](https://issues.apache.org/jira/browse/STREAMPIPES-283). Original Jira may contain additional context.
Reported by: wiener.

**Comment by bossenti** [comment]
Flink is in experimental stage currently
