### ISSUE TITLE
Error when using RuntimeResolvableStaticProperty in an alternative

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#463]
When adding the this code to the declareModel:

Alternatives.from(Labels.withId(ENABLE_GROUPING),
 StaticProperties.group(Labels.withId(GROUP_CONFIG),
 StaticProperties.singleValueSelectionFromContainer(Labels.withId(GROUP_ID_STREAM_1)),
 StaticProperties.singleValueSelectionFromContainer(Labels.withId(GROUP_ID_STREAM_2)))))

 

the following error occurs when the UI tries to resolve the options:

Caused by: org.apache.http.ProtocolException: Target host is not specifiedCaused by: org.apache.http.ProtocolException: Target host is not specified at org.apache.http.impl.conn.DefaultRoutePlanner.determineRoute(DefaultRoutePlanner.java:71) at org.apache.http.impl.client.InternalHttpClient.determineRoute(InternalHttpClient.java:125) at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ... 80 moreorg.apache.http.client.ClientProtocolException at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:187)

 

It seems that the variable this.pipelineElement in BaseRuntimeResolvableInput in the ui is not initialized correctly.

All values of of the REST request in fetchRemoteOptionsForPipelineElement are undefined.

 

Imported from Jira [STREAMPIPES-261](https://issues.apache.org/jira/browse/STREAMPIPES-261). Original Jira may contain additional context.
Reported by: zehnder.

**Comment by alisha-1000** [comment]
Hi @dominikriemer,

I went through the issue and it looks like `RuntimeResolvableStaticProperty` inside `Alternatives` leads to an uninitialized `pipelineElement` in `BaseRuntimeResolvableInput` on the UI side. Because of this, the REST request in `fetchRemoteOptionsForPipelineElement` is constructed with undefined values, resulting in the `Target host is not specified` error.

I’m interested in working on this bug. My initial thought is that the context required for runtime resolution is not correctly propagated when the property is nested inside an `Alternatives` structure.

Please let me know if this issue is still relevant in the current versions and if there are any architectural constraints I should be aware of before starting.
